import pandas as pd


def create_roster_in_game_table():
    roster_in_game = pd.DataFrame(
        columns=[
            "SEASON",
            "DATE",
            "REAL_TEAM_ID",
            "PLAYER_ID",
            "TEAM_ID",
            "AGE",
            "GP",
            "W",
            "L",
            "W_PCT",
            "MIN",
            "FGM",
            "FGA",
            "FG_PCT",
            "FG3M",
            "FG3A",
            "FG3_PCT",
            "FTM",
            "FTA",
            "FT_PCT",
            "OREB",
            "DREB",
            "REB",
            "AST",
            "TOV",
            "STL",
            "BLK",
            "BLKA",
            "PF",
            "PFD",
            "PTS",
            "PLUS_MINUS",
            "DD2",
            "TD3",
        ]
    )
    return roster_in_game


def create_season_record_table():
    season_record = pd.DataFrame(
        columns={
            "SEASON_HOME_GP": [],
            "SEASON_HOME_W": [],
            "SEASON_HOME_L": [],
            "SEASON_HOME_W_PCT": [],
            "SEASON_HOME_PTS": [],
            "SEASON_HOME_W_RANK": [],
            "SEASON_HOME_L_RANK": [],
            "SEASON_HOME_W_PCT_RANK": [],
            "SEASON_HOME_PTS_RANK": [],
            "SEASON_AWAY_GP": [],
            "SEASON_AWAY_W": [],
            "SEASON_AWAY_L": [],
            "SEASON_AWAY_W_PCT": [],
            "SEASON_AWAY_PTS": [],
            "SEASON_AWAY_W_RANK": [],
            "SEASON_AWAY_L_RANK": [],
            "SEASON_AWAY_W_PCT_RANK": [],
            "SEASON_AWAY_PTS_RANK": [],
        }
    )
    return season_record


def create_stats_table():
    template = pd.DataFrame(
        {
            "LAST5_HOME_GAMES": [],
            "LAST5_AWAY_GAMES": [],
            "LAST5_HOME_AS_HOME": [],
            "LAST5_AWAY_AS_AWAY": [],
            "LAST5_HOME_H2H": [],
            "LAST5_HOME_GP": [],
            "LAST5_HOME_W": [],
            "LAST5_HOME_L": [],
            "LAST5_HOME_W_PCT": [],
            "LAST5_HOME_MIN": [],
            "LAST5_HOME_FGM": [],
            "LAST5_HOME_FGA": [],
            "LAST5_HOME_FG_PCT": [],
            "LAST5_HOME_FG3M": [],
            "LAST5_HOME_FG3A": [],
            "LAST5_HOME_FG3_PCT": [],
            "LAST5_HOME_FTM": [],
            "LAST5_HOME_FTA": [],
            "LAST5_HOME_FT_PCT": [],
            "LAST5_HOME_OREB": [],
            "LAST5_HOME_DREB": [],
            "LAST5_HOME_REB": [],
            "LAST5_HOME_AST": [],
            "LAST5_HOME_TOV": [],
            "LAST5_HOME_STL": [],
            "LAST5_HOME_BLK": [],
            "LAST5_HOME_BLKA": [],
            "LAST5_HOME_PF": [],
            "LAST5_HOME_PFD": [],
            "LAST5_HOME_PTS": [],
            "LAST5_HOME_PLUS_MINUS": [],
            "LAST5_AWAY_GP": [],
            "LAST5_AWAY_W": [],
            "LAST5_AWAY_L": [],
            "LAST5_AWAY_W_PCT": [],
            "LAST5_AWAY_MIN": [],
            "LAST5_AWAY_FGM": [],
            "LAST5_AWAY_FGA": [],
            "LAST5_AWAY_FG_PCT": [],
            "LAST5_AWAY_FG3M": [],
            "LAST5_AWAY_FG3A": [],
            "LAST5_AWAY_FG3_PCT": [],
            "LAST5_AWAY_FTM": [],
            "LAST5_AWAY_FTA": [],
            "LAST5_AWAY_FT_PCT": [],
            "LAST5_AWAY_OREB": [],
            "LAST5_AWAY_DREB": [],
            "LAST5_AWAY_REB": [],
            "LAST5_AWAY_AST": [],
            "LAST5_AWAY_TOV": [],
            "LAST5_AWAY_STL": [],
            "LAST5_AWAY_BLK": [],
            "LAST5_AWAY_BLKA": [],
            "LAST5_AWAY_PF": [],
            "LAST5_AWAY_PFD": [],
            "LAST5_AWAY_PTS": [],
            "LAST5_AWAY_PLUS_MINUS": [],
        }
    )
    return template


def columns_to_export(only_drop=False):
    columns = [
        "SEASON",
        "GAME_ID",
        "GAME_DATE",
        "HOME_TEAM_ID",
        "AWAY_TEAM_ID",
        "MATCHUP",
        "HOME_SPREAD",
        "AWAY_SPREAD",
        "HOME_SPREAD_PROB",
        "AWAY_SPREAD_PROB",
        "HOME_MONEYLINE",
        "AWAY_MONEYLINE",
        "HOME_MONEYLINE_DECIMAL",
        "AWAY_MONEYLINE_DECIMAL",
        "OVER_UNDER",
        "HOME_REST_DAYS",
        "AWAY_REST_DAYS",
        "HOME_FATIGUE_LEVEL",
        "AWAY_FATIGUE_LEVEL",
        "HOME_PTS",
        "AWAY_PTS",
        "TOTAL_PTS",
        "HOME_WL",
        "HOME_SPREAD_WL",
        "AWAY_SPREAD_WL",
        "OVER_UNDER_WL",
        "STAR1_HOME",
        "STAR2_HOME",
        "STAR3_HOME",
        "STAR1_AWAY",
        "STAR2_AWAY",
        "STAR3_AWAY",
        "INJURED_STAR1_HOME",
        "INJURED_STAR2_HOME",
        "INJURED_STAR3_HOME",
        "INJURED_STAR1_AWAY",
        "INJURED_STAR2_AWAY",
        "INJURED_STAR3_AWAY",
        "SEASON_HOME_GP",
        "SEASON_HOME_W",
        "SEASON_HOME_L",
        "SEASON_HOME_W_PCT",
        "SEASON_HOME_PTS",
        "SEASON_HOME_W_RANK",
        "SEASON_HOME_L_RANK",
        "SEASON_HOME_W_PCT_RANK",
        "SEASON_HOME_PTS_RANK",
        "SEASON_AWAY_GP",
        "SEASON_AWAY_W",
        "SEASON_AWAY_L",
        "SEASON_AWAY_W_PCT",
        "SEASON_AWAY_PTS",
        "SEASON_AWAY_W_RANK",
        "SEASON_AWAY_L_RANK",
        "SEASON_AWAY_W_PCT_RANK",
        "SEASON_AWAY_PTS_RANK",
        "LAST5_HOME_GAMES",
        "LAST5_AWAY_GAMES",
        "LAST5_HOME_AS_HOME",
        "LAST5_AWAY_AS_AWAY",
        "LAST5_HOME_H2H",
        "LAST5_HOME_GP",
        "LAST5_HOME_W",
        "LAST5_HOME_L",
        "LAST5_HOME_W_PCT",
        "LAST5_HOME_MIN",
        "LAST5_HOME_FGM",
        "LAST5_HOME_FGA",
        "LAST5_HOME_FG_PCT",
        "LAST5_HOME_FG3M",
        "LAST5_HOME_FG3A",
        "LAST5_HOME_FG3_PCT",
        "LAST5_HOME_FTM",
        "LAST5_HOME_FTA",
        "LAST5_HOME_FT_PCT",
        "LAST5_HOME_OREB",
        "LAST5_HOME_DREB",
        "LAST5_HOME_REB",
        "LAST5_HOME_AST",
        "LAST5_HOME_TOV",
        "LAST5_HOME_STL",
        "LAST5_HOME_BLK",
        "LAST5_HOME_BLKA",
        "LAST5_HOME_PF",
        "LAST5_HOME_PFD",
        "LAST5_HOME_PTS",
        "LAST5_HOME_PLUS_MINUS",
        "LAST5_AWAY_GP",
        "LAST5_AWAY_W",
        "LAST5_AWAY_L",
        "LAST5_AWAY_W_PCT",
        "LAST5_AWAY_MIN",
        "LAST5_AWAY_FGM",
        "LAST5_AWAY_FGA",
        "LAST5_AWAY_FG_PCT",
        "LAST5_AWAY_FG3M",
        "LAST5_AWAY_FG3A",
        "LAST5_AWAY_FG3_PCT",
        "LAST5_AWAY_FTM",
        "LAST5_AWAY_FTA",
        "LAST5_AWAY_FT_PCT",
        "LAST5_AWAY_OREB",
        "LAST5_AWAY_DREB",
        "LAST5_AWAY_REB",
        "LAST5_AWAY_AST",
        "LAST5_AWAY_TOV",
        "LAST5_AWAY_STL",
        "LAST5_AWAY_BLK",
        "LAST5_AWAY_BLKA",
        "LAST5_AWAY_PF",
        "LAST5_AWAY_PFD",
        "LAST5_AWAY_PTS",
        "LAST5_AWAY_PLUS_MINUS",
        "HOME_P1_PLAYER",
        "HOME_P1_MIN",
        "HOME_P1_PTS",
        "HOME_P1_AST",
        "HOME_P1_DREB",
        "HOME_P1_OREB",
        "HOME_P1_BLK",
        "HOME_P1_STL",
        "HOME_P1_TOV",
        "HOME_P1_FGA",
        "HOME_P1_FTA",
        "HOME_P1_FG3A",
        "HOME_P1_PF",
        "HOME_P2_PLAYER",
        "HOME_P2_MIN",
        "HOME_P2_PTS",
        "HOME_P2_AST",
        "HOME_P2_DREB",
        "HOME_P2_OREB",
        "HOME_P2_BLK",
        "HOME_P2_STL",
        "HOME_P2_TOV",
        "HOME_P2_FGA",
        "HOME_P2_FTA",
        "HOME_P2_FG3A",
        "HOME_P2_PF",
        "HOME_P3_PLAYER",
        "HOME_P3_MIN",
        "HOME_P3_PTS",
        "HOME_P3_AST",
        "HOME_P3_DREB",
        "HOME_P3_OREB",
        "HOME_P3_BLK",
        "HOME_P3_STL",
        "HOME_P3_TOV",
        "HOME_P3_FGA",
        "HOME_P3_FTA",
        "HOME_P3_FG3A",
        "HOME_P3_PF",
        "HOME_P4_PLAYER",
        "HOME_P4_MIN",
        "HOME_P4_PTS",
        "HOME_P4_AST",
        "HOME_P4_DREB",
        "HOME_P4_OREB",
        "HOME_P4_BLK",
        "HOME_P4_STL",
        "HOME_P4_TOV",
        "HOME_P4_FGA",
        "HOME_P4_FTA",
        "HOME_P4_FG3A",
        "HOME_P4_PF",
        "HOME_P5_PLAYER",
        "HOME_P5_MIN",
        "HOME_P5_PTS",
        "HOME_P5_AST",
        "HOME_P5_DREB",
        "HOME_P5_OREB",
        "HOME_P5_BLK",
        "HOME_P5_STL",
        "HOME_P5_TOV",
        "HOME_P5_FGA",
        "HOME_P5_FTA",
        "HOME_P5_FG3A",
        "HOME_P5_PF",
        "AWAY_P1_PLAYER",
        "AWAY_P1_MIN",
        "AWAY_P1_PTS",
        "AWAY_P1_AST",
        "AWAY_P1_DREB",
        "AWAY_P1_OREB",
        "AWAY_P1_BLK",
        "AWAY_P1_STL",
        "AWAY_P1_TOV",
        "AWAY_P1_FGA",
        "AWAY_P1_FTA",
        "AWAY_P1_FG3A",
        "AWAY_P1_PF",
        "AWAY_P2_PLAYER",
        "AWAY_P2_MIN",
        "AWAY_P2_PTS",
        "AWAY_P2_AST",
        "AWAY_P2_DREB",
        "AWAY_P2_OREB",
        "AWAY_P2_BLK",
        "AWAY_P2_STL",
        "AWAY_P2_TOV",
        "AWAY_P2_FGA",
        "AWAY_P2_FTA",
        "AWAY_P2_FG3A",
        "AWAY_P2_PF",
        "AWAY_P3_PLAYER",
        "AWAY_P3_MIN",
        "AWAY_P3_PTS",
        "AWAY_P3_AST",
        "AWAY_P3_DREB",
        "AWAY_P3_OREB",
        "AWAY_P3_BLK",
        "AWAY_P3_STL",
        "AWAY_P3_TOV",
        "AWAY_P3_FGA",
        "AWAY_P3_FTA",
        "AWAY_P3_FG3A",
        "AWAY_P3_PF",
        "AWAY_P4_PLAYER",
        "AWAY_P4_MIN",
        "AWAY_P4_PTS",
        "AWAY_P4_AST",
        "AWAY_P4_DREB",
        "AWAY_P4_OREB",
        "AWAY_P4_BLK",
        "AWAY_P4_STL",
        "AWAY_P4_TOV",
        "AWAY_P4_FGA",
        "AWAY_P4_FTA",
        "AWAY_P4_FG3A",
        "AWAY_P4_PF",
        "AWAY_P5_PLAYER",
        "AWAY_P5_MIN",
        "AWAY_P5_PTS",
        "AWAY_P5_AST",
        "AWAY_P5_DREB",
        "AWAY_P5_OREB",
        "AWAY_P5_BLK",
        "AWAY_P5_STL",
        "AWAY_P5_TOV",
        "AWAY_P5_FGA",
        "AWAY_P5_FTA",
        "AWAY_P5_FG3A",
        "AWAY_P5_PF",
    ]

    type_ = {
        "SEASON": int,
        "GAME_ID": str,
        "GAME_DATE": str,
        "HOME_TEAM_ID": int,
        "AWAY_TEAM_ID": int,
        "MATCHUP": str,
        "HOME_SPREAD": float,
        "AWAY_SPREAD": float,
        "HOME_SPREAD_PROB": float,
        "AWAY_SPREAD_PROB": float,
        "HOME_MONEYLINE": float,
        "AWAY_MONEYLINE": float,
        "HOME_MONEYLINE_DECIMAL": float,
        "AWAY_MONEYLINE_DECIMAL": float,
        "OVER_UNDER": float,
        "HOME_REST_DAYS": str,
        "AWAY_REST_DAYS": str,
        "HOME_FATIGUE_LEVEL": float,
        "AWAY_FATIGUE_LEVEL": float,
        "HOME_PTS": int,
        "AWAY_PTS": int,
        "TOTAL_PTS": int,
        "HOME_WL": int,
        "HOME_SPREAD_WL": int,
        "AWAY_SPREAD_WL": int,
        "OVER_UNDER_WL": int,
        "STAR1_HOME": str,
        "STAR2_HOME": str,
        "STAR3_HOME": str,
        "STAR1_AWAY": str,
        "STAR2_AWAY": str,
        "STAR3_AWAY": str,
        "INJURED_STAR1_HOME": int,
        "INJURED_STAR2_HOME": int,
        "INJURED_STAR3_HOME": int,
        "INJURED_STAR1_AWAY": int,
        "INJURED_STAR2_AWAY": int,
        "INJURED_STAR3_AWAY": int,
        "SEASON_HOME_GP": int,
        "SEASON_HOME_W": int,
        "SEASON_HOME_L": int,
        "SEASON_HOME_W_PCT": float,
        "SEASON_HOME_PTS": float,
        "SEASON_HOME_W_RANK": int,
        "SEASON_HOME_L_RANK": int,
        "SEASON_HOME_W_PCT_RANK": int,
        "SEASON_HOME_PTS_RANK": int,
        "SEASON_AWAY_GP": int,
        "SEASON_AWAY_W": int,
        "SEASON_AWAY_L": int,
        "SEASON_AWAY_W_PCT": float,
        "SEASON_AWAY_PTS": float,
        "SEASON_AWAY_W_RANK": int,
        "SEASON_AWAY_L_RANK": int,
        "SEASON_AWAY_W_PCT_RANK": int,
        "SEASON_AWAY_PTS_RANK": int,
        "LAST5_HOME_GAMES": float,
        "LAST5_AWAY_GAMES": float,
        "LAST5_HOME_AS_HOME": float,
        "LAST5_AWAY_AS_AWAY": float,
        "LAST5_HOME_H2H": float,
        "LAST5_HOME_GP": int,
        "LAST5_HOME_W": int,
        "LAST5_HOME_L": int,
        "LAST5_HOME_W_PCT": float,
        "LAST5_HOME_MIN": float,
        "LAST5_HOME_FGM": float,
        "LAST5_HOME_FGA": float,
        "LAST5_HOME_FG_PCT": float,
        "LAST5_HOME_FG3M": float,
        "LAST5_HOME_FG3A": float,
        "LAST5_HOME_FG3_PCT": float,
        "LAST5_HOME_FTM": float,
        "LAST5_HOME_FTA": float,
        "LAST5_HOME_FT_PCT": float,
        "LAST5_HOME_OREB": float,
        "LAST5_HOME_DREB": float,
        "LAST5_HOME_REB": float,
        "LAST5_HOME_AST": float,
        "LAST5_HOME_TOV": float,
        "LAST5_HOME_STL": float,
        "LAST5_HOME_BLK": float,
        "LAST5_HOME_BLKA": float,
        "LAST5_HOME_PF": float,
        "LAST5_HOME_PFD": float,
        "LAST5_HOME_PTS": float,
        "LAST5_HOME_PLUS_MINUS": float,
        "LAST5_AWAY_GP": int,
        "LAST5_AWAY_W": int,
        "LAST5_AWAY_L": int,
        "LAST5_AWAY_W_PCT": float,
        "LAST5_AWAY_MIN": float,
        "LAST5_AWAY_FGM": float,
        "LAST5_AWAY_FGA": float,
        "LAST5_AWAY_FG_PCT": float,
        "LAST5_AWAY_FG3M": float,
        "LAST5_AWAY_FG3A": float,
        "LAST5_AWAY_FG3_PCT": float,
        "LAST5_AWAY_FTM": float,
        "LAST5_AWAY_FTA": float,
        "LAST5_AWAY_FT_PCT": float,
        "LAST5_AWAY_OREB": float,
        "LAST5_AWAY_DREB": float,
        "LAST5_AWAY_REB": float,
        "LAST5_AWAY_AST": float,
        "LAST5_AWAY_TOV": float,
        "LAST5_AWAY_STL": float,
        "LAST5_AWAY_BLK": float,
        "LAST5_AWAY_BLKA": float,
        "LAST5_AWAY_PF": float,
        "LAST5_AWAY_PFD": float,
        "LAST5_AWAY_PTS": float,
        "LAST5_AWAY_PLUS_MINUS": float,
        "HOME_P1_PLAYER": str,
        "HOME_P1_MIN": int,
        "HOME_P1_PTS": int,
        "HOME_P1_AST": int,
        "HOME_P1_DREB": int,
        "HOME_P1_OREB": int,
        "HOME_P1_BLK": int,
        "HOME_P1_STL": int,
        "HOME_P1_TOV": int,
        "HOME_P1_FGA": int,
        "HOME_P1_FTA": int,
        "HOME_P1_FG3A": int,
        "HOME_P1_PF": int,
        "HOME_P2_PLAYER": str,
        "HOME_P2_MIN": int,
        "HOME_P2_PTS": int,
        "HOME_P2_AST": int,
        "HOME_P2_DREB": int,
        "HOME_P2_OREB": int,
        "HOME_P2_BLK": int,
        "HOME_P2_STL": int,
        "HOME_P2_TOV": int,
        "HOME_P2_FGA": int,
        "HOME_P2_FTA": int,
        "HOME_P2_FG3A": int,
        "HOME_P2_PF": int,
        "HOME_P3_PLAYER": str,
        "HOME_P3_MIN": int,
        "HOME_P3_PTS": int,
        "HOME_P3_AST": int,
        "HOME_P3_DREB": int,
        "HOME_P3_OREB": int,
        "HOME_P3_BLK": int,
        "HOME_P3_STL": int,
        "HOME_P3_TOV": int,
        "HOME_P3_FGA": int,
        "HOME_P3_FTA": int,
        "HOME_P3_FG3A": int,
        "HOME_P3_PF": int,
        "HOME_P4_PLAYER": str,
        "HOME_P4_MIN": int,
        "HOME_P4_PTS": int,
        "HOME_P4_AST": int,
        "HOME_P4_DREB": int,
        "HOME_P4_OREB": int,
        "HOME_P4_BLK": int,
        "HOME_P4_STL": int,
        "HOME_P4_TOV": int,
        "HOME_P4_FGA": int,
        "HOME_P4_FTA": int,
        "HOME_P4_FG3A": int,
        "HOME_P4_PF": int,
        "HOME_P5_PLAYER": str,
        "HOME_P5_MIN": int,
        "HOME_P5_PTS": int,
        "HOME_P5_AST": int,
        "HOME_P5_DREB": int,
        "HOME_P5_OREB": int,
        "HOME_P5_BLK": int,
        "HOME_P5_STL": int,
        "HOME_P5_TOV": int,
        "HOME_P5_FGA": int,
        "HOME_P5_FTA": int,
        "HOME_P5_FG3A": int,
        "HOME_P5_PF": int,
        "AWAY_P1_PLAYER": str,
        "AWAY_P1_MIN": int,
        "AWAY_P1_PTS": int,
        "AWAY_P1_AST": int,
        "AWAY_P1_DREB": int,
        "AWAY_P1_OREB": int,
        "AWAY_P1_BLK": int,
        "AWAY_P1_STL": int,
        "AWAY_P1_TOV": int,
        "AWAY_P1_FGA": int,
        "AWAY_P1_FTA": int,
        "AWAY_P1_FG3A": int,
        "AWAY_P1_PF": int,
        "AWAY_P2_PLAYER": str,
        "AWAY_P2_MIN": int,
        "AWAY_P2_PTS": int,
        "AWAY_P2_AST": int,
        "AWAY_P2_DREB": int,
        "AWAY_P2_OREB": int,
        "AWAY_P2_BLK": int,
        "AWAY_P2_STL": int,
        "AWAY_P2_TOV": int,
        "AWAY_P2_FGA": int,
        "AWAY_P2_FTA": int,
        "AWAY_P2_FG3A": int,
        "AWAY_P2_PF": int,
        "AWAY_P3_PLAYER": str,
        "AWAY_P3_MIN": int,
        "AWAY_P3_PTS": int,
        "AWAY_P3_AST": int,
        "AWAY_P3_DREB": int,
        "AWAY_P3_OREB": int,
        "AWAY_P3_BLK": int,
        "AWAY_P3_STL": int,
        "AWAY_P3_TOV": int,
        "AWAY_P3_FGA": int,
        "AWAY_P3_FTA": int,
        "AWAY_P3_FG3A": int,
        "AWAY_P3_PF": int,
        "AWAY_P4_PLAYER": str,
        "AWAY_P4_MIN": int,
        "AWAY_P4_PTS": int,
        "AWAY_P4_AST": int,
        "AWAY_P4_DREB": int,
        "AWAY_P4_OREB": int,
        "AWAY_P4_BLK": int,
        "AWAY_P4_STL": int,
        "AWAY_P4_TOV": int,
        "AWAY_P4_FGA": int,
        "AWAY_P4_FTA": int,
        "AWAY_P4_FG3A": int,
        "AWAY_P4_PF": int,
        "AWAY_P5_PLAYER": str,
        "AWAY_P5_MIN": int,
        "AWAY_P5_PTS": int,
        "AWAY_P5_AST": int,
        "AWAY_P5_DREB": int,
        "AWAY_P5_OREB": int,
        "AWAY_P5_BLK": int,
        "AWAY_P5_STL": int,
        "AWAY_P5_TOV": int,
        "AWAY_P5_FGA": int,
        "AWAY_P5_FTA": int,
        "AWAY_P5_FG3A": int,
        "AWAY_P5_PF": int,
    }
    return columns, type_


def columns_to_drop(drop_data_x_darko=True):
    drop_x_all = [
        "SEASON",
        "GAME_ID",
        "GAME_DATE",
        "MATCHUP",
        "HOME_REST_DAYS",
        "AWAY_REST_DAYS",
        "HOME_PTS",
        "AWAY_PTS",
        "TOTAL_PTS",
        "STAR1_HOME",
        "STAR2_HOME",
        "STAR3_HOME",
        "STAR1_AWAY",
        "STAR2_AWAY",
        "STAR3_AWAY",
        "LAST5_HOME_GAMES",
        "LAST5_AWAY_GAMES",
        "HOME_P1_PLAYER",
        "HOME_P2_PLAYER",
        "HOME_P3_PLAYER",
        "HOME_P4_PLAYER",
        "HOME_P5_PLAYER",
        "AWAY_P1_PLAYER",
        "AWAY_P2_PLAYER",
        "AWAY_P3_PLAYER",
        "AWAY_P4_PLAYER",
        "AWAY_P5_PLAYER",
    ]

    drop_x_darko = [
        "HOME_P1_MIN",
        "HOME_P1_PTS",
        "HOME_P1_AST",
        "HOME_P1_DREB",
        "HOME_P1_OREB",
        "HOME_P1_BLK",
        "HOME_P1_STL",
        "HOME_P1_TOV",
        "HOME_P1_FGA",
        "HOME_P1_FTA",
        "HOME_P1_FG3A",
        "HOME_P1_PF",
        "HOME_P2_MIN",
        "HOME_P2_PTS",
        "HOME_P2_AST",
        "HOME_P2_DREB",
        "HOME_P2_OREB",
        "HOME_P2_BLK",
        "HOME_P2_STL",
        "HOME_P2_TOV",
        "HOME_P2_FGA",
        "HOME_P2_FTA",
        "HOME_P2_FG3A",
        "HOME_P2_PF",
        "HOME_P3_MIN",
        "HOME_P3_PTS",
        "HOME_P3_AST",
        "HOME_P3_DREB",
        "HOME_P3_OREB",
        "HOME_P3_BLK",
        "HOME_P3_STL",
        "HOME_P3_TOV",
        "HOME_P3_FGA",
        "HOME_P3_FTA",
        "HOME_P3_FG3A",
        "HOME_P3_PF",
        "HOME_P4_MIN",
        "HOME_P4_PTS",
        "HOME_P4_AST",
        "HOME_P4_DREB",
        "HOME_P4_OREB",
        "HOME_P4_BLK",
        "HOME_P4_STL",
        "HOME_P4_TOV",
        "HOME_P4_FGA",
        "HOME_P4_FTA",
        "HOME_P4_FG3A",
        "HOME_P4_PF",
        "HOME_P5_MIN",
        "HOME_P5_PTS",
        "HOME_P5_AST",
        "HOME_P5_DREB",
        "HOME_P5_OREB",
        "HOME_P5_BLK",
        "HOME_P5_STL",
        "HOME_P5_TOV",
        "HOME_P5_FGA",
        "HOME_P5_FTA",
        "HOME_P5_FG3A",
        "HOME_P5_PF",
        "AWAY_P1_MIN",
        "AWAY_P1_PTS",
        "AWAY_P1_AST",
        "AWAY_P1_DREB",
        "AWAY_P1_OREB",
        "AWAY_P1_BLK",
        "AWAY_P1_STL",
        "AWAY_P1_TOV",
        "AWAY_P1_FGA",
        "AWAY_P1_FTA",
        "AWAY_P1_FG3A",
        "AWAY_P1_PF",
        "AWAY_P2_MIN",
        "AWAY_P2_PTS",
        "AWAY_P2_AST",
        "AWAY_P2_DREB",
        "AWAY_P2_OREB",
        "AWAY_P2_BLK",
        "AWAY_P2_STL",
        "AWAY_P2_TOV",
        "AWAY_P2_FGA",
        "AWAY_P2_FTA",
        "AWAY_P2_FG3A",
        "AWAY_P2_PF",
        "AWAY_P3_MIN",
        "AWAY_P3_PTS",
        "AWAY_P3_AST",
        "AWAY_P3_DREB",
        "AWAY_P3_OREB",
        "AWAY_P3_BLK",
        "AWAY_P3_STL",
        "AWAY_P3_TOV",
        "AWAY_P3_FGA",
        "AWAY_P3_FTA",
        "AWAY_P3_FG3A",
        "AWAY_P3_PF",
        "AWAY_P4_MIN",
        "AWAY_P4_PTS",
        "AWAY_P4_AST",
        "AWAY_P4_DREB",
        "AWAY_P4_OREB",
        "AWAY_P4_BLK",
        "AWAY_P4_STL",
        "AWAY_P4_TOV",
        "AWAY_P4_FGA",
        "AWAY_P4_FTA",
        "AWAY_P4_FG3A",
        "AWAY_P4_PF",
        "AWAY_P5_MIN",
        "AWAY_P5_PTS",
        "AWAY_P5_AST",
        "AWAY_P5_DREB",
        "AWAY_P5_OREB",
        "AWAY_P5_BLK",
        "AWAY_P5_STL",
        "AWAY_P5_TOV",
        "AWAY_P5_FGA",
        "AWAY_P5_FTA",
        "AWAY_P5_FG3A",
        "AWAY_P5_PF",
    ]

    drop_x_home_moneyline = [
        "HOME_SPREAD_WL",
        "AWAY_SPREAD_WL",
        "OVER_UNDER_WL",
    ]

    drop_x_home_spread = [
        "HOME_WL",
        "AWAY_SPREAD_WL",
        "OVER_UNDER_WL",
    ]

    drop_x_away_spread = [
        "HOME_WL",
        "HOME_SPREAD_WL",
        "OVER_UNDER_WL",
    ]

    drop_x_over_under = [
        "HOME_WL",
        "HOME_SPREAD_WL",
        "AWAY_SPREAD_WL",
    ]
    if(drop_data_x_darko==True):
        drop_x_all = drop_x_all + drop_x_darko
    
    return drop_x_all + drop_x_home_moneyline, drop_x_all + drop_x_home_spread, drop_x_all + drop_x_away_spread, drop_x_all + drop_x_over_under